name: Enforce File Changes in PRs

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-required-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for required file changes
        run: |
          # List the required files
          REQUIRED_FILES=(
            "automaticffl-for-woocommerce.php"
            "changelog.txt"
            "readme.txt"
          )

          # Get the list of modified files
          MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD)

          # Check if required files are modified
          for FILE in "${REQUIRED_FILES[@]}"; do
            if ! echo "$MODIFIED_FILES" | grep -q "$FILE"; then
              echo "Error: $FILE must be modified in the PR."
              exit 1
            fi
          done

          echo "All required files are modified."
